### ISSUE TITLE
Docking Tube Suggestion

### ISSUE THREAD

**Issue by JC3371** [GingerWalnut/SQ5.0Public#103]
I made my docking tower out of prismarine and it doesn't work. Zorecknor helped test it and it works on any other block besides prismarine.

**Comment by soronthar** [comment]
I tested a bunch of ship-allowed blocks, and docking tubes worked only with wool, dyed terracota and concrete.

**Comment by JC3371** [comment]
Will this be implemented then?

**Comment by JC3371** [comment]
I see no advantage of having different blocks for docking tubes

**Comment by martinjonsson01** [comment]
Suggestions are not a priority, bugs are given higher priority and will most likely be fixed first.

**Comment by JC3371** [comment]
I understand that but will you take this into consideration or no?

**Comment by martinjonsson01** [comment]
Don't see a reason why we can't add this in the future.

**Comment by JC3371** [comment]
Ok, cool.

**Comment by GingerWalnut** [comment]
Next restart will allow any block to be the frame
