### ISSUE TITLE
Drills not mining colored blocks properly(Known @ Kattadi)

### ISSUE THREAD

**Issue by TheMindaugas** [GingerWalnut/SQ5.0Public#106]
Drilled teracotta blocks lose their color data and become white teracotta blocks. Same thing is suspected with wool and other blocks that have additional data bound to them.

**Comment by Seamonster778778778788** [comment]
not a bug, intended so u buy PREMIUM PAINTER

**Comment by martinjonsson01** [comment]
This is a bug.

**Comment by GingerWalnut** [comment]
Fixed
