### ISSUE TITLE
I get stuck when I pilot a ship sometimes

### ISSUE THREAD

**Issue by IggyW** [GingerWalnut/SQ5.0Public#108]
So each time I pilot a ship it freezes me in place, and I cant fly the ship at all. A relog didn't help, and breaking a ship sign and making a new one didnt help either.

**Comment by IggyW** [comment]
This only happens sporadically by the way...

**Comment by martinjonsson01** [comment]
What causes this, how can we reproduce it?

**Comment by IggyW** [comment]
I have no idea, it seems to be random and caused possibly by server lag, but it hasnt happened enough for me to do major testing on it
