### ISSUE TITLE
chat spam from colony

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQ5.0Public#111]
when i broke a sign it triggered a lot of spam in chat, a colony that i have perms in.
I also hit a slime
![image](https://user-images.githubusercontent.com/34897864/34892425-db3e602e-f79e-11e7-86bc-83bb9448f5d7.png)

**Comment by GingerWalnut** [comment]
Shhhh, is only temporary

**Comment by GingerWalnut** [comment]
Should be fixed
