### ISSUE TITLE
Furnace Glitch

### ISSUE THREAD

**Issue by Invaderchaos** [GingerWalnut/SQ5.0Public#113]
Every time I put items in a furnace causing it to start smelting, it immediately closes the furnace window without me manually closing it. At first this glitch seemed like a minor hinderance, but it can also cause one to lose items. For instance, I had 56 dark oak logs, and I shift clicked only one piece of dark oak in the fuel slot. Since this activated the furnace, it kicked me out of the furnace window, but it also caused me to lose the 55 remaining dark oak logs my mouse was holding at the moment it kicked me out of the furnace window. I am pretty sure this applies to the top slot as well. Thanks!

**Comment by soronthar** [comment]
I can confirm this happens on colony claims. Outside colonies is working fine.

**Comment by TheMindaugas** [comment]
Happens to me too, please fix.

**Comment by martinjonsson01** [comment]
Possibly related to #63

**Comment by GingerWalnut** [comment]
Should be fixed
