### ISSUE TITLE
Placing any SQTech machine will replace the block currently in that space

### ISSUE THREAD

**Issue by swils24** [GingerWalnut/SQ5.0Public#115]
Repro:  Place blocks that have gaps between their edges, and the bounding box of a normal block-size.  EG, stack two chests on top of each other.  Right click with an SQT machine on the top of the bottom chest, and it will replace the top chest with the SQT block.

Additionally/tangent, right clicking any SQT block to interact with it, will place whichever block you are currently holding.  EDIT: not 100% of the time.  At least happens with auto shearers

**Comment by GingerWalnut** [comment]
Fixed
