### ISSUE TITLE
Drills be borked

### ISSUE THREAD

**Issue by IggyW** [GingerWalnut/SQ5.0Public#117]
![2018-01-12_20 26 56](https://user-images.githubusercontent.com/19827420/34902783-55dc0e7a-f7d7-11e7-9955-8414f8bb09d7.png)
Activate a drill. The gold block immediately turns into a chest, turning it into a doublechest and making the drill not move. In addition, when you click the drill, the GUI no longer pops up, and when you break the drill, nothing drops.

**Comment by GingerWalnut** [comment]
Should be fixed

**Comment by IggyW** [comment]
Please un-close this, it happened again to at least 6 of my drills.

**Comment by IggyW** [comment]
And... it happened to the rest of my drills. It seems to only happen inside colonies. Outside colonies, the drill bit just pops off the drill, so its equally useless, although at least you dont lose a gold block

**Comment by GingerWalnut** [comment]
Fixed
