### ISSUE TITLE
Leaves don't seem to decay on Canora

### ISSUE THREAD

**Issue by jorcool** [GingerWalnut/SQ5.0Public#121]
On Canora, Birch leaves from the normal birch trees don't decay. They just keep dropping saplings but don't actually go away. It's very annoying because trees don't grow under them and it's gamebreaking because you just get new saplings

**Comment by martinjonsson01** [comment]
Does this only happen inside of colonies, or everywhere @jorcool ?

**Comment by jorcool** [comment]
alright, problem solved. stuff goes away again
