### ISSUE TITLE
"You need a space suit to breath" (inside)

### ISSUE THREAD

**Issue by Invaderchaos** [GingerWalnut/SQ5.0Public#128]
Hello,
I just noticed after taking my spacesuit off in colony(inside a closed area) that whenever I start sprinting around it says I need a spacesuit. This is only a minor bug b/c I don't actually start suffocating, but it does fill up my chat. Thank you! I can send an image for reference, if needed. Thank you!

**Comment by martinjonsson01** [comment]
Is your colony in space? Also, what is the distance from you to the walls and ceiling?

**Comment by Invaderchaos** [comment]
Yes, my colony is in space. It happens at varying distances from walls and the ceiling, but usually it happens when I am in a 3x3 tunnel. It occurs most often when I am at the highest point of a sprint jump.
