### ISSUE TITLE
Auto-Farms after latest SQTech update.

### ISSUE THREAD

**Issue by Hagen-Bryz** [GingerWalnut/SQ5.0Public#134]
All farms covered in dirt after the latest update when i got on.

![capture](https://user-images.githubusercontent.com/35397000/34963615-201ed650-fa52-11e7-865e-be2056633b00.PNG)

**Comment by Hagen-Bryz** [comment]
If the farm has power - the dirt gets repalced as soon as I break it untill it runs out of power

**Comment by GingerWalnut** [comment]
Fixed for next restart
