### ISSUE TITLE
1 Million Missing From colony Bank

### ISSUE THREAD

**Issue by Cutout1** [GingerWalnut/SQ5.0Public#135]
I mentioned this in staff chat, but figured I should make a post here about it too. Earlier today I deposited some money into my colony and I remember the balance being just a bit over one million credits, which is about what I try to keep it at all the time. Then, later today I checked again and it was at only 37,500 credits, which was really strange because somehow in the course of one day my colony balance went down like a million credits when my upkeep is only 40k a day, and I didn't claim like 1000 chunks or something. I don't know when it actually happened, so I don't have much info for you to troubleshoot off of, but it's something to be looked into.

**Comment by Cutout1** [comment]
I think I just realized the cause. Do federations cost 1 million to found? Because I made a federation today on a whim lol

**Comment by GingerWalnut** [comment]
That would do it
