### ISSUE TITLE
Shield Didn't Protect Blocks

### ISSUE THREAD

**Issue by Cutout1** [GingerWalnut/SQ5.0Public#136]
I had a ship with 2 shields and 7 cannons and 6 thrusters and I got in a fight with a much larger ship with many more cannons and stuff. For some reason my shield rather than protecting from at least a couple shots from this larger ship immediately started blowing up, even though the shield bar in the top of the screen still said 100%. There was also a duping issue related to this, but Bloo apparently already reported this in a PM, so I won't talk about that here.

**Comment by Generaltyler1** [comment]
had a similar issue as well, my shield bar still said 100% but I was watching my ship get blown up behind me, and after I managed to get back to base, lives told me he heard the sound of the shield breaking, even though my shield bar still said it was at 100%

**Comment by GingerWalnut** [comment]
If I had to guess, the shield bar is left-over and you actually didn't have 100% shields and/or a shield generator. The shield breaking sound is just that I made explosion sounds happen whenever blocks are destroyed so you know you are under attack.

**Comment by Cutout1** [comment]
No, I definitely had a shield generator, in fact I had two. Both fully charged

**Comment by GingerWalnut** [comment]
Potential fix for this, reopen if it happens again
