### ISSUE TITLE
Music volume does not change

### ISSUE THREAD

**Issue by Creepopolous** [GingerWalnut/SQ5.0Public#137]
For some reason, the music that plays on the 'Players' channel does not seem to change volume, unless that slider is at zero. Other sounds tied to that bar do change, such as the sound that plays when picking up items, but the music remains at a deafening high level. I have not yet checked if changing the 'Master Volume' level has any effect.

**Comment by GingerWalnut** [comment]
Minecraft issue, cannot fix. Will change it to the music slider at some point to see if that fixes it once I remove normal minecraft music
