### ISSUE TITLE
Blocks within ships underwater get deleted

### ISSUE THREAD

**Issue by Creepopolous** [GingerWalnut/SQ5.0Public#138]
If someone were to place a block inside their ship, pilot their ship without redetecting, and autopilot away, those blocks would go missing. This doesn't happen in the air, but if your ship is submerged, they disappear as soon as you move away.

**Comment by martinjonsson01** [comment]
So what you're saying is that it doesn't remove blocks, it only removes liquids. Right? @Creepopolous

**Comment by Creepopolous** [comment]
Actually, I'm saying it removes both. I had droppers stocked with crops, and they disappeared. I tried again with pumpkins- they disappeared too.

**Comment by GingerWalnut** [comment]
Fixed for next restart
