### ISSUE TITLE
Starship sizes

### ISSUE THREAD

**Issue by FlyingTaurus523** [GingerWalnut/SQ5.0Public#14]
I believe we're supposed to get larger ships once we rank up but that isn't working

**Comment by GingerWalnut** [comment]
Fixed for next restart

**Comment by martinjonsson01** [comment]
Fix not working.

**Comment by martinjonsson01** [comment]
Oops my bad, fix hasn't been put on server yet. Will be fixed next time *Ginger restarts the server.
