### ISSUE TITLE
Colored Glass not preventing cross-streams during piping

### ISSUE THREAD

**Issue by swils24** [GingerWalnut/SQ5.0Public#144]
Using a single path of colored glass works fine, but when you have any colored glass blocks adjacent (but not attached to the same nodes), item transport gets wonky, and you end up with items in the wrong tube systems.  Example repro:
![image](https://user-images.githubusercontent.com/7865593/35101713-79f51468-fc2e-11e7-9c82-6fa08389650f.png)

**Comment by GingerWalnut** [comment]
Fixed
