### ISSUE TITLE
SUGGESTION: disallow space colonies

### ISSUE THREAD

**Issue by SomethingSomethingAllison** [GingerWalnut/SQ5.0Public#145]
This was talked about in starquest's discord today, and since people were starting to get tired of me talking about it, I've decided to just suggest it: disallow space colonies!

I have many reasons to think this, and I've done my best to think about it in 3 ways.

General reasons:
Space has no mobs, so theres no challenge to players.
Space has all ores and ores tend to be worth more than farming.
Almost all of the space colonies are in the south, closer to spawn.
Since these colonies are closer to spawn, they don't need to worry about being attacked.
Modules are built from ores, meaning space colony members almost never need to move.
Anything the colony can't get they can just by from other colonies, meaning they can just stay in space forever.

Colonist reasons:
as said above, ores usually sale more than other items, so they get more credits from being lazy.
as also said above, most of the colonies are closer to spawn, which means they can easily avoid pirates.

so there is no challenge to them other than gravity and space suits, which is easily avoidable, and they'd get MORE than they would if they were on a planet, to me that doesn't sound balanced.

Pirate reasons:
pirates can easily just stalk space 24/7 and never have to leave.
pirates can also use space colonies to easily kill new players.
space colonies can also be used to stop ships in colony claims.
pirates can camp spawn easily because most of the current space claims are already near spawn.

in the end, there is almost no point on going to planets other than getting resources, and I can see more people moving to space in the future. I can see this becoming a problem and the only solution I see is just disallowing colony claims in space all together, its already been like this in the past. I see the intention of allowing players more freedom in where they choose to live, but in the end, space colonies are just gonna give more power to people that want to be lazy and live closer to spawn, which has never been a good thing, and it still isn't.

**Comment by GingerWalnut** [comment]
Done in next release
