### ISSUE TITLE
Got roughly a third the credit amount in reputation rather than half

### ISSUE THREAD

**Issue by Cutout1** [GingerWalnut/SQ5.0Public#150]
I sold 2 stacks of diamond and a stack of gold at spawn for 180k credits, but I noticed the reputation I recieved was only 59k defalos rep or so and nothing else. Unless I'm mistaken, it's supposed to be half, right?
![2018-01-19_20 34 42](https://user-images.githubusercontent.com/10093818/35179916-2fb64468-fd59-11e7-85c5-388d861eb8ab.png)

**Comment by Cutout1** [comment]
Update: I'm noticing the same thing with Klon, I just sold some klon items for 120k credits and got only 44k rep

**Comment by JC3371** [comment]
One of my members got 200k credits and only 35k rep in vapid :/

**Comment by Cutout1** [comment]
It seems to work fine if you only sell one type of item at a time, didn't thoroughly test that though so I may be wrong

**Comment by martinjonsson01** [comment]
Is this intentional, @GingerWalnut ?

**Comment by LucasKintao** [comment]
Can confirm. Putting only iron in my inv would've given me the exact amount, but after adding another item (gold) rep changed to roughly 1/3rd money. removing the gold from the sell GUI brought the values to the right proportion again

**Comment by GingerWalnut** [comment]
Fixed
