### ISSUE TITLE
mining gets you duplicate blocks - low chance

### ISSUE THREAD

**Issue by Generaltyler1** [GingerWalnut/SQ5.0Public#156]
Earlier today I was converting concrete powder into solid concrete when I first noticed that I was occasionally getting an extra concrete block, out of 16 stacks I got like an extra 8 blocks, but later when I was drilling I would get an extra wood plank when I was picking up the drills, and now not to long ago, still picking up drills I ended up getting an extra gold block.

**Comment by Generaltyler1** [comment]
so far it happens when I "break" a block, it drops the block but the main block is still there, and I can break it again for another block. happens in colonies so far

**Comment by Cutout1** [comment]
I found this bug too, I was trying to figure it out and could only get it to work for slabs and stairs in my testing for some reason, didn't test too far though.

**Comment by soronthar** [comment]
This happened to me inside my colony, with wood and wooden slabs.

**Comment by Seamonster778778778788** [comment]
happens to me a lot with non solid blocks like chests and signs

**Comment by Seamonster778778778788** [comment]
happens more often

**Comment by GingerWalnut** [comment]
Should be fixed
