### ISSUE TITLE
Singular node ceasing to work

### ISSUE THREAD

**Issue by UnrelatedString** [GingerWalnut/SQ5.0Public#159]
A transport node I recently placed under an autofarm chest on Canora, which I believe is the first I have placed since the addition of filters, transported one half stack of wheat before ceasing to function. After replacing it it continued not to function.

**Comment by UnrelatedString** [comment]
A second node has been affected and nothing is being imported when the nodes that do still export do so.

**Comment by GingerWalnut** [comment]
Should be fixed
