### ISSUE TITLE
Modules defaulting to Spawners

### ISSUE THREAD

**Issue by swils24** [GingerWalnut/SQ5.0Public#16]
Still occurring, seemingly randomly. Appears to happen across the entirety of a ship, but not to all ships on the server at once.

**Comment by GingerWalnut** [comment]
Any idea why this is occuring? Is there any pattern to it, such as when leaving a planet?

**Comment by swils24** [comment]
I've seen it occur most frequently at un/re-piloting, or when using helm signs

**Comment by GingerWalnut** [comment]
Ah, that would make sense as those are the times when blockdata "transfers hands" so to speak

**Comment by Seamonster778778778788** [comment]
will sometimes drop xp, and the item

**Comment by GingerWalnut** [comment]
This seems to have been resolved. please open a new issue if this occurs again. Please note that modules may infact look fixed and still be broken, so make sure to check them by right clicking on them. If a GUI does not open, they are already broken.
