### ISSUE TITLE
Shield glitch

### ISSUE THREAD

**Issue by realMrZilla** [GingerWalnut/SQ5.0Public#161]
Sometimes when moving my ship the shields randomly reset to 0% and stay there. sometimes when I keep moving it comes back to 100% but most of the time it stays at 0%. Repiloting fixes this. Idk if this has an actual influence on the shield's protection or if its just a display issue

**Comment by realMrZilla** [comment]
Update: yes they don't provide protection anymore, my ship has a hole now because of bugged shields -.-"

**Comment by Seamonster778778778788** [comment]
this is fixed atleast to my knowledge @GingerWalnut

**Comment by GingerWalnut** [comment]
Seems this has been fixed. If it starts again, please open a new issue
