### ISSUE TITLE
Items Jamming in SQ Tech Pipes for no Reason

### ISSUE THREAD

**Issue by Laserlance141** [GingerWalnut/SQ5.0Public#163]
Basically title. It only happens in some pipes, and continued happening in the same pipe even after replacing all the parts, rerouting a major part of the pipe, and changing the color of the glass. The items just jam in parts for no reason, and then even after breaking and replacing the glass, it will just get jammed again. I have built other pipes in the same general area, and they work, but other smaller pipes that were placed in the exact same route of the pipeline didn't work. 
Possible root of problem: The database that stores the data on which items are where in the pipeline somehow gets sightly corrupted, or just doesn't update properly, causing that space in the world to be forever broken. I don't know how this happens, but I do have an area in the world that could be used for testing (StarGazer Tower Store Room Black Pipeline). If you need anymore info, please ask me and ill try to explain the things that I know happened before this problem started to try to pin down the root of the problem.

**Comment by ironjim92** [comment]
same problem here, replaced the pipes multiple times but items just get stuck.

**Comment by GingerWalnut** [comment]
Fixed, bug with items not wanting to go up/down after going down/up
