### ISSUE TITLE
drill glitch

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQ5.0Public#165]
drills sometime obtain regular stone instead of cobble, from stone (maybe intended somehow?)
drills also do not do blockupdates so torches can float, and lava and water do not update, and stay in place if mined by
reproduce:
drill
(noticed on sabaka)

**Comment by soronthar** [comment]
Drills sometimes drop stone from one of the variants (I think its andesite), that may be what you are seeing.

**Comment by GingerWalnut** [comment]
Fixed for next restart
