### ISSUE TITLE
Modules and Ship Signs taking on random appearances

### ISSUE THREAD

**Issue by swils24** [GingerWalnut/SQ5.0Public#17]
Modules often go to looking like an axe or pig or invisible.
Ship signs often go to looking like a module, or invisible.
Both remain functional and appear properly upon relogging.

**Comment by GingerWalnut** [comment]
Not sure there is much I can do unforunatly. Pretty sure its a minecraft bug, but I will keep my eyes open for a solution.

**Comment by GingerWalnut** [comment]
Found a way to get around it.
