### ISSUE TITLE
Misc bugs

### ISSUE THREAD

**Issue by LivesParkkk** [GingerWalnut/SQ5.0Public#170]
1-Taxes being improperly collected (It has been 5 days and taxes have been collected twice)

2- I entered the south east planet warp on kattadi and promptly suffocated inside the wall of my ship. was told to github it by maritn.

3- Happened to multiple people while flying today in space- entire ship disappeared apart from modules. rest of ship was still "there" as ghost blocks, levitated slightly above the ground. Fixed by a relog.

4- Radar Residue (already raised by seamonster)

5- Hard to duplicate but happens seemingly at random module dupe glitch involving ------- (Pmed to ginger)

6- Sometimes when shift flying my shields drop to 0 percent (only tested when multiple shield modules are on the ship)

7-Sometimes even if my shields say 100% i will unpilot my ship at base after being shot once or twice and have chunks missing.

8- Rep acquired by selling items to spawn is 1/4 rep:credits right now where it should be 1/2.

**Comment by martinjonsson01** [comment]
We'd prefer it if you could separate bugs into different issues, that way we can organize them much better.

**Comment by GingerWalnut** [comment]
The rep bug is fixed.

**Comment by GingerWalnut** [comment]
Most of these should be fixed, open individual issues if any of them are still problems.
