### ISSUE TITLE
Being spammed with permission to build/ break blocks in colony

### ISSUE THREAD

**Issue by Cutout1** [GingerWalnut/SQ5.0Public#175]
While flying my ship, and only while flying my ship, even if I'm not in a colony I get spammed with the message "You do not have permission to break blocks in this colony! You do not have permission to build blocks in this colony" Actually it might not only be when I'm flying, but it happens much more often in my ship at least.

**Comment by Cutout1** [comment]
EDIT: Definitely happens even when I'm not flying a ship, and it's even worse now.

**Comment by martinjonsson01** [comment]
What triggered this?

**Comment by Cutout1** [comment]
I have no idea, I wasn't even near a colony, i was in spawn when it happened. It's stopped now though.

**Comment by ironjim92** [comment]
im having same issue

**Comment by GingerWalnut** [comment]
Should be fixed
