### ISSUE TITLE
Slipdrive, Jammer and Torpedo Textures on SQLITE

### ISSUE THREAD

**Issue by LucasKintao** [GingerWalnut/SQ5.0Public#181]
Needs to be added. Only seen them in the full text pack so far.

**Comment by realMrZilla** [comment]
Those textures are added. You should download the newest version of it.

**Comment by martinjonsson01** [comment]
Latest lite resource pack is available [here](http://www.spacebeaverstudios.com/resources/resource-packs/sqlite) (apply this first)
Latest full resource pack is available [here](http://www.spacebeaverstudios.com/resources/resource-packs/sqfull)
