### ISSUE TITLE
Falling into void in slipspace

### ISSUE THREAD

**Issue by TNTCurrent01** [GingerWalnut/SQ5.0Public#182]
A few minutes ago, while riding my ship in slipspace I somehow managed to fall off of it and plummeted straight into the void with nothing to stop me. There should be a safety mechanism in place (like there is in the overworld) that prevents players from falling below Y=0 and dying due to lag falls.

Will look favorably upon the implementation of such a safety mechanism :)

**Comment by GingerWalnut** [comment]
This shouldn't be an issue as you don't actually move in slipspace, it just updates your regular world location... Odd that it is. Will look into it

**Comment by GingerWalnut** [comment]
This should be fixed
