### ISSUE TITLE
Jammer just "freezes" the autopilot

### ISSUE THREAD

**Issue by realMrZilla** [GingerWalnut/SQ5.0Public#183]
When you activate the jammer on someone autopiloting, they do stop moving but their speed stays "frozen" in the health bar. And as soon you disable the jammer, for example to catch up with someone, they can just continue flying, starting with full speed without having to turn their autopilot back on. I tested this by jamming my own ship. This is what it looks like: https://imgur.com/a/FP9sb

**Comment by realMrZilla** [comment]
Also why does it say Slipdrive cannot be activated? lol just noticed.

**Comment by GingerWalnut** [comment]
This has been "fixed"
