### ISSUE TITLE
Federations cannot invite other colonies to join

### ISSUE THREAD

**Issue by IggyW** [GingerWalnut/SQ5.0Public#187]
When I do /fed invite <colony name>, regardless of which colony I choose to invite, it says "You have invited StarGazer to join your federation!" followed by "Your colony has been invited to join the StarCorp federation"... 
So its inviting my own colony to join the federation we founded...

**Comment by martinjonsson01** [comment]
Federations aren't finished and in the state that they are in on the server currently they are practically useless, so functionality of the plugin isn't guaranteed. I'll close this for now, and if this issue persists after we release the official version of Federations then comment here again and I'll reopen it.
