### ISSUE TITLE
Transfer Nodes Borked

### ISSUE THREAD

**Issue by callum24689** [GingerWalnut/SQ5.0Public#188]
Simply put the contents won't transfer. If you mine the pipe contents from the chest drop though, it's as if contents are getting stuck in the tubing.
Thanks

**Comment by martinjonsson01** [comment]
Are you using double chests? SQTech has been having trouble with those so try using single chests.

**Comment by callum24689** [comment]
I’m using single chests.

**Comment by GingerWalnut** [comment]
Should be fixed
