### ISSUE TITLE
/Rank possibly misbehaving

### ISSUE THREAD

**Issue by swils24** [GingerWalnut/SQ5.0Public#19]
Ranked up to what I thought was "Electrician" in Klon.  /drank only showed me as a Handyman.  When I had ranked up, it told me I had ranked up to Electrician. Using /rank showed me at electrician. No relogging fixed this. Ranked up again (to the 1mil cred/rank tier) and was again told that I had ranked up to electrician. Now /drank displays electrician properly.

**Comment by GingerWalnut** [comment]
Will be fixed at next restart
