### ISSUE TITLE
Canora exiting issue

### ISSUE THREAD

**Issue by n0807701j2d2** [GingerWalnut/SQ5.0Public#190]
I was flying out of Canora and I managed to get into space, but when I moved, I was teleported back to the 3rd quartile of the planet. When I flew back out, I was in the same place in space as before, and so on until I tried flying a couple thousand blocks East on Canora, then managed to successfully fly way from Canora. I had no error messages, seems like the planet TP boxes are a bit strangely configured.

**Comment by n0807701j2d2** [comment]
My IGN is Jurgmania. Martin asked me to post this after I told him about it in SQ chat. There was a similar discussion going on about people on Arenstad but Martin suggested it could be a different bug

**Comment by GingerWalnut** [comment]
This has been fixed to my knowledge, open this again if it still occurs.
