### ISSUE TITLE
Broken Transfer Pipes

### ISSUE THREAD

**Issue by n0807701j2d2** [GingerWalnut/SQ5.0Public#191]
I have a 5x3 array of chests with transfer nodes on my autofarms. I have them connected in one line with the nodes on the pipes, not through the pipes. At the end of this line is a node importing wheat; all the other exports are correctly set. 

The chests are filled with the exporting material, but none of them are emptying; no change seen in the import chest.

I will not try breaking the pipes to fix it because I have done this several times.

**Comment by n0807701j2d2** [comment]
Jurgmania again

**Comment by martinjonsson01** [comment]
Are you using doublechests? SQTech has had trouble with those previously.

**Comment by n0807701j2d2** [comment]
Not using double chests

**Comment by GingerWalnut** [comment]
Should be fixed
