### ISSUE TITLE
Arenstad Server Transfer Glitch

### ISSUE THREAD

**Issue by JC3371** [GingerWalnut/SQ5.0Public#192]
When I flew out of Arenstad, I spawned too close to Arenstad and we're stuck outside of the planet as server jump is failing. Additionally, it says that we are encountering an obstacle about 5000 blocks away from where we are so...

**Comment by n0807701j2d2** [comment]
When I try exiting Arenstad, I get an error message:

The worldjump has failed
Encountered an obstacle at -5769.5, 100, 2441.5

I flew a couple hundred blocks around Arenstad and finally I was able to exit the planet.

Jurgmania again, and I've posted something similar about Canora

**Comment by martinjonsson01** [comment]
Possibly related to #190

**Comment by JC3371** [comment]
From the last time I tested this, you have to fly out to about the center of the planet so that you have enough distance after exiting the planet to actually fly away without being instantly teleported back in.

**Comment by JC3371** [comment]
Now on Arenstad, I have to fly to the center of the planet to go into space. My bases is towards the west side of the planet and if I try exiting there it will say Worldjump failed and blocked at some coordinates.

**Comment by CrazyCreeper1o1** [comment]
I do believe there is just a ship blocking the server jump in the south-west quartile of Arenstad

**Comment by GingerWalnut** [comment]
I think this has been fixed, open a new issue if this still occurs
