### ISSUE TITLE
Ship Module Glitch

### ISSUE THREAD

**Issue by JC3371** [GingerWalnut/SQ5.0Public#194]
One of my ships that's about 1.4k blocks has this weird glitch where it has 6/30 modules even though there are none on the ship. After placing modules that take up 24 module slots it has hit the max limit. I talked to Nevlo and he said there must be some invisible modules or something in my ship that's taking up slots. No relogging, replacing modules, or redetecting will change the problem.

**Comment by JC3371** [comment]
This ship was created like 2-3 days ago

**Comment by GingerWalnut** [comment]
Any new instances of this issue should be fixed. If it occurs again, open a new issue.
