### ISSUE TITLE
Docking Tube buttons and Boarding Ramps get lost after using them then piloting

### ISSUE THREAD

**Issue by swils24** [GingerWalnut/SQ5.0Public#20]
Parking your ship and then using either docking tube or boarding ramp will seemingly disconnect the functional blocks from your ship when you repilot.  Buttons or the stairs+wool will linger in place and not fly with your ship after being used.  Redetecting ship (while still in place and aligned with the retracted blocks) will fix/work properly.

**Comment by GingerWalnut** [comment]
Boarding Ramps are fixed for next restart

**Comment by GingerWalnut** [comment]
Fixed docking tubes
