### ISSUE TITLE
territories or forts sometime just never show anymore

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQ5.0Public#211]
![image](https://user-images.githubusercontent.com/34897864/37982227-a7a05762-31b5-11e8-91e6-6d8b4888a427.png)

**Comment by martinjonsson01** [comment]
We did not write the dynmap, we can not solve any dynmap-related bugs that are not caused by our set up of the territories. The best we can do is create some form of workaround.

Does refreshing the page not fix it?
