### ISSUE TITLE
Cannot upgrade colony from Outpost

### ISSUE THREAD

**Issue by Gaming4me** [GingerWalnut/SQ5.0Public#217]
made a colony on my alt 3 days ago, been trying to upgrade it from outpost ever since, but always get greeted with the following message:

![image](https://user-images.githubusercontent.com/11284568/38104548-d6d4b8ec-335f-11e8-8c07-32c10b6b3eb5.png)
I've tried upgrading from my main and asking Deacs to try and do it for me, with no luck.

**Comment by GingerWalnut** [comment]
This should be fixed
