### ISSUE TITLE
Ship goes faster with more weight

### ISSUE THREAD

**Issue by Bonzer1uk** [GingerWalnut/SQ5.0Public#224]
![2018-04-13_01 20 56](https://user-images.githubusercontent.com/14862423/38710631-49cd198e-3eb9-11e8-989e-14b7e41d29f0.png)
![2018-04-13_01 20 58](https://user-images.githubusercontent.com/14862423/38710633-4bfcf788-3eb9-11e8-9d04-bb357a517791.png)

The ship goes faster with more weight

**Comment by GingerWalnut** [comment]
The 15950 ship has three more blocks. Each block adds a small amount of thrust to the ship so that it can go the default speed if it was all wool
