### ISSUE TITLE
Module Limit Exceeded

### ISSUE THREAD

**Issue by littlebroOM** [GingerWalnut/SQ5.0Public#230]
I went to fix some of the modules from last night's break. I separated a ship from all attaching blocks, whether ship blocks or not. I removed every single module on the ship, and yet it still says that the ship has 11/12 modules on it already.

Breaking sign, redetecting, etc didn't fix.

**Comment by liv4ths** [comment]
So I found out that sometimes modules get "stuck" in blocks when doing this. Ive had to break wool blocks to find the modules, sometimes a wool block and module both will drop when breaking the wool block. I think the system counts those wool blocks with the modules "inside" them

**Comment by GingerWalnut** [comment]
All new cases of this bug should be fixed. If there is a **new** case of it, make sure to open up a new issue.
