### ISSUE TITLE
ship button are extremely laggy

### ISSUE THREAD

**Issue by starmask1** [GingerWalnut/SQ5.0Public#234]
lets say you are parking a ship
you get close to the docking tube
and you get stuck on a button and it spams you with a "if you want to leave type /shipexit"
if you are to type it you fall and 90%die from it
its a thing that goes in sq for a while and im surprised i am the only one to github it
please try fixing it
thanks

**Comment by GingerWalnut** [comment]
This will be fixed at next restart
