### ISSUE TITLE
Heavy Freighters not working

### ISSUE THREAD

**Issue by liv4ths** [GingerWalnut/SQ5.0Public#236]
So I was trying to move my Heavy Freighter and it won't move at all no shift flying or autopilot. I tried re-logging, re-detecting, breaking the sign. It doesn't say anything is blocking it just won't move, plus it locks me to the ship and won't let me move either. Then if I unpilot it causes me to "fly" until i re-log.

**Comment by GingerWalnut** [comment]
This should be fixed at next restart (hopefully)
