### ISSUE TITLE
Rep glitch

### ISSUE THREAD

**Issue by JC3371** [GingerWalnut/SQ5.0Public#24]
A couple of days ago, I sold ores and it went into the vapid corp. Now it sells correctly into the defalos corp. The problem is that all of my rep is in the vapid corp, 37k and I only have 5k in defalos. I need it to be transferred over to defalos.

**Comment by JC3371** [comment]
I also have two people who can vouch for me.

**Comment by martinjonsson01** [comment]
Was this resolved, or why did you close the issue?

**Comment by JC3371** [comment]
Resolved
