### ISSUE TITLE
Problems with the colony permissions

### ISSUE THREAD

**Issue by Sofetios** [GingerWalnut/SQ5.0Public#242]
I have a permission set made called "Members". In it I made it so the default rank in this permission set can break, place, all perms. I set the permission set up on 9 chunks that make up a 3x3. this is supposed to be so anyone who joins the colony can build in that 3x3 and do stuff there. i had my first colony member, jayturn test placing there. it worked fine. about 5 minutes later or so, he told me he couldn't place or break or anything. i went over and saw that it was true. i hadn't changed around with the permissions. Though i did look through permissions when he was able to sheer my sheep in a chunk in which all perms were supposed to be set to false him. it all was correct, so i am confused. For the sheep part, i have global perm set set to all false. the only places he should have been able to do stuff in was two chunks that i gave to him, and the 3x3 chunk for all colony members. 

Also when i tried to delete the permission set I made, it wouldnt wowrk. i would hit the red circle with a line through it for deleting it, and nothing happened. no error message or anything, just did nothing.

**Comment by GingerWalnut** [comment]
I've done some stuff with this in the next update, so if this is still a thing, reopen an issue
