### ISSUE TITLE
machines broke

### ISSUE THREAD

**Issue by Sofetios** [GingerWalnut/SQ5.0Public#243]
Hey, i just tried mining my sheep auto farmer and generator, when it broke, all i got was xp orbs. the machine didn't become the item. i couldn't right click them either. It treated them like a mob spawner with no mobs.

**Comment by GingerWalnut** [comment]
Either this was before the hotfix that I made that fixed some of the blockdata, or these blocks were placed after the backup was taken. Unfortunatly, all you can do is ask for a refund.
