### ISSUE TITLE
Thick Plating On Power Armor Doesn't Seem To Work

### ISSUE THREAD

**Issue by Cutout1** [GingerWalnut/SQ5.0Public#246]
I was testing power armor with Nevlo, and we found that tier 3 power armor with level 5 thick plating on each piece was far worse than prot 4 diamond. We think this is because thick plating isn't working, but we never actually tested it without thick plating.

**Comment by GingerWalnut** [comment]
Not really a duplicate, but the other issue at the top fills this role
