### ISSUE TITLE
Dynmap

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQ5.0Public#258]
See i dont know if this is a minecraft thing, or a server thing, but a lot of times peoples skins don't work in-game, and no matter what dynmap never shows actual playerheads, its shows alex or steve.

**Comment by brickworm2012** [comment]
The ingame skins issue is often the fault of the client (your own files). The Dynmap issue has to do with the dynamic map coding itself and isn't controlled by the devs. Generally if there's been a name or skin change, the program doesn't know how to find the new information, and so uses the default.

**Comment by GingerWalnut** [comment]
There isn't much we can do for the client side part of this, but a new update for dynmap came out a day ago that should fix this issue. Expect it on the server with the next major update.
