### ISSUE TITLE
Suffocating in ships

### ISSUE THREAD

**Issue by buba141** [GingerWalnut/SQ5.0Public#265]
I was trying out my corvette for the first time, and I died due to suffocation damage, even though I was in a ship. I only took damage when I was standing on a carpet. I also started floating like I was spacewalking.

**Comment by JUSAPlayer1** [comment]
I've noticed this too. Wasnt sure if it was a glitch or intended.

**Comment by GingerWalnut** [comment]
This should be fixed for the next update
