### ISSUE TITLE
Damage not being taken in federated colonies

### ISSUE THREAD

**Issue by skarph** [GingerWalnut/SQ5.0Public#269]
Description: Only can melee attack (no bow, no guns) when in federated colonies when one is in a non-federated colony, greatly hindering SvS and PvP.

Repro steps:

1. Have person A be in a non-federated colony, and have person B be in a federated colony
2. Have person A use a non-melee attack on person B
3. Person B takes no damage

**Comment by GingerWalnut** [comment]
Fixed for next update
