### ISSUE TITLE
Ban Apeal

### ISSUE THREAD

**Issue by Matt11thsmith** [GingerWalnut/SQ5.0Public#282]
Hello all to those who know me and who do not,
It is Smp or my current in Kaph_, I am deeply sorry for what I had said while I was in sq, I had been going through a bunch of irl stuff, so I took a few months to reflect b4 I create this thread, if if not intend to do the following, "rule lawyering" and ginger my intent was to help YOUR rules so that others would not try to bend rules, I am apsaultly willing to help with your rules, so rule lawyering does not happen in the future, I did say that the death of sq was eminate yes, but alas those where the exact words of Starmask that I was repeating, but I'm not here to put blame on anyone else, I want to shoulder the burden upon myself for I said it, but I would appreciate it very much IF you would consider revoking the ban, and keeping an eye on me for a period of time set later to where if I upset a mod for any reason that goes against any of your rules I will be permabanned and will not apeal again, again I am deeply sorry for all the things I have said in the past
Yours truly Smp

**Comment by martinjonsson01** [comment]
Send a DM to oldskool#4015 on Discord to appeal. GitHub is only for bug reports.
