### ISSUE TITLE
Ships leave behind light blocks

### ISSUE THREAD

**Issue by Laserlance141** [GingerWalnut/SQ5.0Public#33]
Wherever a ship flew, light blocks get left behind, causing anywhere it flies to be illuminated like the surface.
These light blocks cannot be removed, as placing and removing a block from where they has no effect. 
Probably stems from ships not wanting to cause lighting updates as they fly through the sky.

**Comment by GingerWalnut** [comment]
Will not be fixed as it would cause a lot of lag to fix this.
