### ISSUE TITLE
Sheep aren't spawning on Arenstad

### ISSUE THREAD

**Issue by JC3371** [GingerWalnut/SQ5.0Public#34]
I've looked everywhere in a 400 block radius and there are no sheep in sight.

**Comment by JC3371** [comment]
This is specifically near the UCLOF colony in the valleys

**Comment by JC3371** [comment]
So far I've seen 2 sheep in this large radius

**Comment by soronthar** [comment]
Could it be that there are one too many sheep farms, so when they are loaded the passive mob cap is reached?

**Comment by Tongonto** [comment]
More sheep should spawn now; instead of just blocking other passive mobs from spawning, sheep will spawn in their place
