### ISSUE TITLE
Colony Perms Bug

### ISSUE THREAD

**Issue by Rufiani** [GingerWalnut/SQ5.0Public#36]
In a Specific chunk the Chunk perms will not show up or not work. And in that chunk no perms will work for any ranks.

Another bug I have found is when I delete a Global Perm Set in the menu, I have found out how to take out the Barrier block when you delete the perm set and use it as a real block (placing, putting it in inventory slots) just as any other block.

**Comment by GingerWalnut** [comment]
Probably fixed, please let me know if it isn't
