### ISSUE TITLE
Colony Deposit all Dupe Glitch

### ISSUE THREAD

**Issue by BlackcloneYT** [GingerWalnut/SQ5.0Public#51]
As I got done selling stuff to the shop I did the deposit all to the colony. When I checked my bal to see if it went through I see it was still there so I did the command again And it was all my money like 12602.21 And I keep doing it and I was confused. When I checked /conolny Info It duped it So from 17400 Or something like that to 160k

**Comment by GingerWalnut** [comment]
Will be fixed next restart
