### ISSUE TITLE
Every time I log on I'm in local chat

### ISSUE THREAD

**Issue by TheLoneTraveler** [GingerWalnut/SQ5.0Public#52]
Every time I've logged on, I've been put in local chat despite logging off in global chat.  I am on Arenstad and I don't know if it's a problem on other planets.

**Comment by soronthar** [comment]
I have the same issue.  I have to move to global every time I log

**Comment by martinjonsson01** [comment]
Most likely some configuration value we need to change.
If it turns out to be a bug then we still can't fix it since we use a plugin from a third-party.

**Comment by GingerWalnut** [comment]
Changed Chat plugin
