### ISSUE TITLE
Can make ships over 500 blocks, but won't allow me to pilot it after first detection

### ISSUE THREAD

**Issue by IggyW** [GingerWalnut/SQ5.0Public#59]
So I am making a ship thats obviously over 500 blocks.
When I put down the ship sign and detect it for the first time, it says I have boarded the ship, and I can move around. When I unpilot it, I can no longer use the ship unless I break the ship sign and remake the sign. (It says "Exceeds maximum allowable blocks, must have 50 or less")

**Comment by GingerWalnut** [comment]
Should be fixed for next restart
