### ISSUE TITLE
Modules drop xp sometimes as well as the module block

### ISSUE THREAD

**Issue by IggyW** [GingerWalnut/SQ5.0Public#60]
It seems to be pretty random, three out of four of my shields did it but only a couple of my 12 thrusters.

**Comment by realMrZilla** [comment]
This is because the server started lagging again. I'm guessing that there are too many machines powered even though only the ones in loaded chunks are working.

**Comment by GingerWalnut** [comment]
Should be fixed on next restart. However, it will also keep xp from dropping from blocks like ores. Will work on a solution for that.
