### ISSUE TITLE
Ship Protection Bug

### ISSUE THREAD

**Issue by GoldPikachuSpark** [GingerWalnut/SQ5.0Public#62]
Cannot break blocks of ships with ship protection or any ship blocks that may be connected to it. Have to repilot in order to be able to access those inventories or break the blocks again. Once the ship enables its protection the whole thing starts over and any blocks that happen to be connected to the ship cannot be opened or broken.

**Comment by Elttob** [comment]
Can confirm. You can't interact with blocks such as trapdoors when a ship is protected, requiring you to replace the ship sign to fix.

**Comment by GingerWalnut** [comment]
Fixed
