### ISSUE TITLE
Furnace Eating Ores

### ISSUE THREAD

**Issue by flaammeer** [GingerWalnut/SQ5.0Public#63]
The furnace was in my ship (not in use while flying) after placing the ores in i noticed something different about the furnace its back was to me i got most of the ore smelted then the coal ran down inside of it i was in the inventory of the furnace and it flipped from the backside to the front side with it the ore missing didnt lose much ore so its not a big deal but i dont want someone to lose their resources due to it

**Comment by GingerWalnut** [comment]
I'm not sure I can fix this unforunatly. Seems like a sponge bug.

**Comment by GingerWalnut** [comment]
Found a way to fix it.
