### ISSUE TITLE
Ships Merging

### ISSUE THREAD

**Issue by Rufiani** [GingerWalnut/SQ5.0Public#69]
Today, Blockbuster019 and myself (Rufiani) were having a few friendly Ship Vs Ship battles on Arenstad, until I Autopiloted into his ship and we merged, part of my ship was left on parts of his ship (and the blocks did not regenerate)

Later that day Tiat and Bonzer were Ship Vs Ship battling Myself (Rufiani) And Blockbuster019 until again we merged, my ships bottom and nose was left on his top of his ship. Please fix this bug.

Also, I'm fairly sure it's because we autopiloted into each other that caused the merging

![2018-01-04_15 02 41](https://user-images.githubusercontent.com/34927280/34547507-86f4edce-f160-11e7-9c1b-b3c6fcee4f56.png)

![2018-01-04_15 02 44](https://user-images.githubusercontent.com/34927280/34547510-87535a4e-f160-11e7-80c4-6c6693ab429f.png)

![2018-01-04_15 02 46](https://user-images.githubusercontent.com/34927280/34547511-87b0e952-f160-11e7-81ff-8adfa99d905a.png)

![2018-01-04_15 02 48](https://user-images.githubusercontent.com/34927280/34547512-880bcdae-f160-11e7-8445-9759f8982a7e.png)

![2018-01-04_15 02 51](https://user-images.githubusercontent.com/34927280/34547514-886f19c2-f160-11e7-921c-2a2e33f1da2b.png)

![2018-01-04_15 02 56](https://user-images.githubusercontent.com/34927280/34547515-88cfd834-f160-11e7-846a-338b06d0210b.png)

![2018-01-04_15 02 58](https://user-images.githubusercontent.com/34927280/34547516-8938308c-f160-11e7-9d18-ebe5ad188f48.png)

![2018-01-04_15 03 10](https://user-images.githubusercontent.com/34927280/34547517-8996af5e-f160-11e7-8336-20cf63ddb196.png)

![2018-01-04_15 03 13](https://user-images.githubusercontent.com/34927280/34547518-89ef517c-f160-11e7-8200-6712ee50a83b.png)

![2018-01-04_15 03 16](https://user-images.githubusercontent.com/34927280/34547519-8a4907d0-f160-11e7-9479-ad6672014ab8.png)

![2018-01-04_15 03 25](https://user-images.githubusercontent.com/34927280/34547520-8aa55ef4-f160-11e7-92ca-b14b9f066ecf.png)

![2018-01-04_15 03 31](https://user-images.githubusercontent.com/34927280/34547521-8b01e412-f160-11e7-8957-0b1b02eb12c2.png)

![2018-01-04_15 02 38](https://user-images.githubusercontent.com/34927280/34547526-9085ac52-f160-11e7-8a52-a052ffdad326.png)

**Comment by GingerWalnut** [comment]
Made a fix that should make this issue happen much less frequently, if at all.
