### ISSUE TITLE
Sheep Farm Issues

### ISSUE THREAD

**Issue by rocky0121** [GingerWalnut/SQ5.0Public#70]
I made a sheep farm (this was after the Sqtech update), and it worked for a bit. After that, I came back, bred more sheep, and waited for around thirty minutes, and it didn't work. I replaced the sheep farm block with a new one I had crafted, and supplied it with energy. I checked it, and it worked, but after waiting around 2 hours it stopped working, and that's where I'm at. Not sure whats wrong, but could be a bug. On a separate note, I'm not sure if this is an intended feature, but transfer nodes only transfer to one chest inventory even when hooked up to a double chest. In other words, the chest only fills up halfway automatically, and does not fill the rest of the chest.

**Comment by GingerWalnut** [comment]
From the sounds of it, it seems like its operator error. I really need to get a guide out there since its a bit non-intuitive.
