### ISSUE TITLE
Shipmodules not dropping

### ISSUE THREAD

**Issue by realMrZilla** [GingerWalnut/SQ5.0Public#71]
When you break Shipmodules they will not drop at the moment. Boop__Beep and me lost 2 Thrusters through this problem.

**Comment by martinjonsson01** [comment]
Did they still look like thrusters when you broke them, or had they turned into pig spawners like in #16 ?

**Comment by realMrZilla** [comment]
they still looked like normal Thrusters

**Comment by martinjonsson01** [comment]
Alright won't mark as duplicate of #16 then, but it's possible that fixing #16 will fix this one.

**Comment by GingerWalnut** [comment]
They can still look like they should and be borked. The texture only breaks if you move it on a ship. If you right click on the block and it doens't open a gui then its borked. This is more than likely that problem, so I am closing it. Feel free to open a new issue if non-borked ship modules don't drop items.

**Comment by martinjonsson01** [comment]
Got it. Duplicate of #16
