### ISSUE TITLE
Droppers losing  content

### ISSUE THREAD

**Issue by soronthar** [GingerWalnut/SQ5.0Public#77]
Sometimes droppers are losing part or all of its content. It seems to happen when traveling to/from space, and happened on different planets.

**Comment by rocky0121** [comment]
i can confirm this happened to me as well on arenstad, but the contents reappeared after a repilot

**Comment by Jarkyc** [comment]
can confirm this happened to me 2 times, during the leaving and entering of planets. Mods helped me though.

**Comment by GingerWalnut** [comment]
Possible fix for this at the next restart

**Comment by GingerWalnut** [comment]
Going to close this since I havn't heard a report of this recently, open a new issue if it is still happening
