### ISSUE TITLE
Lost Colony Perms

### ISSUE THREAD

**Issue by Stuffsss** [GingerWalnut/SQ5.0Public#80]
I created a colony with a friend of mine and now neither of us have the permissions to claim land, set permissions, or withdraw funds from our colony. Can you update it so that there has to be at least one person in a colony of the founder position that has permissions to do everything?

**Comment by GingerWalnut** [comment]
Message me when your online so I can troubleshoot it. Additionally, what is the name of your colony?

**Comment by Stuffsss** [comment]
My colony is called SpaceKoalas, and I'm going to be on all day Saturday and Sunday this weekend

**Comment by GingerWalnut** [comment]
This issue in general should be fixed at the next restart
