### ISSUE TITLE
Dropper Issues

### ISSUE THREAD

**Issue by UsaidM22** [GingerWalnut/SQ5.0Public#83]
After finishing my mining trip on Kattadi, I loaded my droppers piloted my ship. Right as I did this, the server crashed. When I logged back on, all the items I had put into my droppers were gone. After being refunded (thanks to Cutout, and Martin), I flew over to Cutout's base for some business. Once I landed, I once again noticed that some of the items in my dropper were missing. I found this extremely odd, because the first time there was an actual excuse, but the second time for raises a red flag.

**Comment by martinjonsson01** [comment]
Any way to reproduce this?

**Comment by IggyW** [comment]
I dont know but this has happened to me too, where random droppers in my ship suddenly lose their items.

**Comment by martinjonsson01** [comment]
@IggyW did that happen after a server crash, or during normal flight? If it happened during normal flight then #88 is the correct issue.

**Comment by IggyW** [comment]
okay it is #88

**Comment by GingerWalnut** [comment]
Possible fix for this at the next restart

**Comment by GingerWalnut** [comment]
If this is still occuring, open a new issue
