### ISSUE TITLE
flying

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQ5.0Public#84]
![image](https://user-images.githubusercontent.com/34897864/34646288-745de6fa-f329-11e7-9232-c3d70b7b23bd.png)
user can fly on a planet due to a glitch
cant change Y value
fixed by relog

**Comment by soronthar** [comment]
Two players were killed in space, they both have properly built cryos, but they spawned in the planet in the clouds. After relog they fell to the ocean.

**Comment by martinjonsson01** [comment]
Not really relevant to this issue? More relevant to #86

**Comment by GingerWalnut** [comment]
Fixed
