### ISSUE TITLE
Cryopods not working

### ISSUE THREAD

**Issue by APnaptime** [GingerWalnut/SQ5.0Public#86]
I died with a cryopod made the day prior. Upon respawn the message was something along the lines of your thingy being obstructed and ended up at spawn. This was on sabaka

**Comment by GingerWalnut** [comment]
Did you go back and check that the cryopod wasn't tampered with?

**Comment by JC3371** [comment]
This has happened to me as well, giving the same msg. However I did get respawned back at the cryopod.

**Comment by GingerWalnut** [comment]
Are there any new instances of this happening today/late yesterday?

**Comment by GingerWalnut** [comment]
Closing until it can be verified that this is occuring still.
