### ISSUE TITLE
Dissapearing items from droppers

### ISSUE THREAD

**Issue by Sofetios** [GingerWalnut/SQ5.0Public#88]
this has happened twice now where i load my 12 droppers full of carrots and potatoes and then fly them directly to spawn. upon arrival and opening the droppers, around half the items are gone. I dont know if it is something to do with leaving the planet or what but i cant reliably use droppers. There was not time window where someone could have taken any, even invisibly.

**Comment by martinjonsson01** [comment]
Similar to #83 but not caused by a server crash. Won't mark as duplicate.

**Comment by GingerWalnut** [comment]
Duplicate of #77
