### ISSUE TITLE
Invisible & Invulnerable entitys

### ISSUE THREAD

**Issue by Laserlance141** [GingerWalnut/SQ5.0Public#9]
Bascally title, like what happens with that boat I showed you. An entity like this can still have a hitbox glitching you out, or can just not allow you to place blocks where it exists.

**Comment by Laserlance141** [comment]
Found an invulnerable skeleton 
![2017-12-24_20 04 42](https://user-images.githubusercontent.com/13091148/34332569-f54fbbaa-e8e6-11e7-8064-53e9bd1109bd.png)

**Comment by GingerWalnut** [comment]
Any idea why this occurs?

**Comment by GingerWalnut** [comment]
Haven't had a report of this happening recently, open a new issue if it happens again
