### ISSUE TITLE
Sheep despawning

### ISSUE THREAD

**Issue by JC3371** [GingerWalnut/SQ5.0Public#90]
After breeding sheep I saw some sheep despawn right in front of me. It seems that they disappear when some limit is reached in a chunk.

**Comment by JC3371** [comment]
And sometimes they just pop back in as well.

**Comment by JC3371** [comment]
Eventually it goes back to the original number of sheep but they keep despawning and respawning in a never-ending cycle

**Comment by GingerWalnut** [comment]
Do you have a sheep farmer?

**Comment by JC3371** [comment]
I do, but I'm currently not using it

**Comment by GingerWalnut** [comment]
It might be it, "eating" sheep and then uneating them when sheep get too far away etc. I think this still happens even without using energy. Sounds like a normal behavior. I think deacs has a video coming out soon explaining sheep farmers.

**Comment by martinjonsson01** [comment]
So, confirmed Not A Bug then?

**Comment by GingerWalnut** [comment]
Probably, send a screenshot of the area where it is occuring to make sure first?

**Comment by martinjonsson01** [comment]
@JC3371 ^

**Comment by JC3371** [comment]
Zorecknor took a video of it. He said that he would upload it here, but he hasn't so far.

**Comment by soronthar** [comment]
Sorry for the late post

[Here is the video]https://vimeo.com/250386497)

**Comment by martinjonsson01** [comment]
Yeah, have you seen the latest SQTech tutorial by Deacs and Ginger? It explains how sheep farms work and how they automatically remove sheep from the pen to decrease lag. https://youtu.be/7yFKoM_ILE8

**Comment by JC3371** [comment]
I did not have my sheep farm running at that moment.

**Comment by JC3371** [comment]
It also took down like half of my sheep at a time.

**Comment by GingerWalnut** [comment]
Expected behavior. The sheep farm still makes virtual sheep even if it isn't receiving power. It additionally also only does it every few ticks to cause less lag from scanning for sheep.
