### ISSUE TITLE
Ship speed nerf & weapon sounds

### ISSUE THREAD

**Issue by realMrZilla** [GingerWalnut/SQ5.0Public#91]
Somehow my ships got a nerf in speed today. My fast ship was nerfed from 15 bps to 9, and my battleship from 12 to 1 bps so I had to replace the ship to get the original speed back. 
Also cannon fire sounds seem to not work (atleast for me).

**Comment by GingerWalnut** [comment]
Make sure your thrusters are working, its possible that they broke. Cannon fire sound has been switched to a new custom sound, but the resourcepack with the actual sound update has not been released yet. Still have a couple of things I'd like to add/change before I make everyone update their resourcepack a couple of times.

**Comment by realMrZilla** [comment]
If the thrusters would've been broke, would i have been able to fix them by just replacing the ship sign?

**Comment by GingerWalnut** [comment]
No, you would have to make sure that they hadn't been turned into spinny pigs or spinny pigs in disguise (aka borked). To detect a spinny pig in disguise, right click on a thruster and see if it brings up a gui. If it doesn't, its borked.

**Comment by realMrZilla** [comment]
Ok i just checked, they are not borked and the gui opens just like normal. For some reson they changed their direction facing though :/

**Comment by martinjonsson01** [comment]
We've made several weight changes this past week, when did this decrease in speed happen?

**Comment by GingerWalnut** [comment]
The speed system is due for a major balance/revamp in any event. Chances are they will change again soon.

**Comment by realMrZilla** [comment]
i noticed it around 2 hours ago when i logged on first. Also my ships were still alright when i flew them yesterday.

**Comment by GingerWalnut** [comment]
Seems to be an issue with a recent blockdata change. YOu only need to redetect to fix it
