### ISSUE TITLE
sqtech autocrafter isnt taking my eggs from nearby chests

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQ5.0Public#94]

**Comment by martinjonsson01** [comment]
Does this only apply to eggs, have you tried with other items? Are you using those weird 32 stacks of eggs from #89 ? @Seamonster778778778788

**Comment by Seamonster778778778788** [comment]
ive only noticed it with eggs and no i am not

**Comment by GingerWalnut** [comment]
Fixed
