### ISSUE TITLE
Redstone in Colonies is acting strange

### ISSUE THREAD

**Issue by soronthar** [GingerWalnut/SQ5.0Public#99]
There are several redstone-relates issues in colonies:

- Pressure plates and buttons once activated do not deactivate (i.e they keep emiting redstone signal).
- Dispensers with Water Buckets are not placing the water (the source block do not appear in the world, but the bucket is emptied), and spitting out the bucket.
- Repeaters and Comparators are not receiving redstone signals from levers or dust.
- Observers are not detecting normal block updates in front of them. 
- If the block in front of the observer is powered by redstone (via button, lever, etc) then it activates, and it remain activated even when broken and placed back (seems that the "powered" state of the block in front of it is nevercleared, even when broken)

**Comment by soronthar** [comment]
Another weird behavior: Sometimes repeaters keep powered even after the redstone signal is removed. But instead of a single pulse, it pulse every other redstone tick

**Comment by Laserlance141** [comment]
I think i also have seen this happen, a repeater froze up and caused a filter to dump all the items from my input line into the dirt bulk storage. I tried updating it once i noticed, but i had to break and rebuild the whole filter. After that it worked again.

**Comment by GingerWalnut** [comment]
Fixed

**Comment by martinjonsson01** [comment]
Still occuring accoring to #112

**Comment by GingerWalnut** [comment]
Seems to have been actually fixed this time
